services:
  postgres:
    image: postgres:16-alpine
    container_name: myapp_db_dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-myapp}
    volumes:
      - myapp_data_dev:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: myapp_app_dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-myapp}
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  myapp_data_dev:
